# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e463e265ae5bb97964daced91497ef4cd95d820b544bc749d985924de12affae4b1ef651f6bcb427619c122f1f93547afcdedbd5e77b61ae46b6e184a59788d

test:
  secret_key_base: 198891b43475b414085e31ed71b109871120c6be62cf13cbdc0b8f437e365c483158448e0bf17fc88d1aca4dc665045724f34526eceac38e10d128550aa404fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
